Repository DocStory/backend, pull requests merged in 2025-03, with the labels that each got.

#2 [Set]: Neo4j 세팅
  build.gradle
  src/main/java/com/ky/docstory/config/Neo4jConfig.java
  src/main/java/com/ky/docstory/controller/Neo4jTestController.java
  src/main/resources/application.properties
Labels: 🛠️setting

#6 [Feat]: 공통 응답 포맷 & 글로벌 예외 처리
  src/main/java/com/ky/docstory/common/code/DocStoryResponseCode.java
  src/main/java/com/ky/docstory/common/dto/DocStoryResponseBody.java
  src/main/java/com/ky/docstory/common/exception/BusinessException.java
  src/main/java/com/ky/docstory/common/exception/GlobalExceptionHandler.java
  src/main/java/com/ky/docstory/controller/UserController.java
  src/main/java/com/ky/docstory/service/UserService.java
Labels: 🛠️setting

#11 [Feat]: Swagger 초기 설정
  build.gradle
  src/main/java/com/ky/docstory/config/SwaggerConfig.java
  src/main/java/com/ky/docstory/controller/UserController.java
Labels: 🛠️setting

#12 [Feat]: Swagger-ui 경로 설정
  src/main/resources/application.properties
Labels: 🛠️setting

#16 [Feat]: 소셜 로그인 구현
  .gitignore
  build.gradle
  docker-compose.yml
  src/main/java/com/ky/docstory/auth/CurrentUser.java
  src/main/java/com/ky/docstory/auth/CustomOAuth2User.java
  src/main/java/com/ky/docstory/auth/CustomOAuth2UserService.java
  src/main/java/com/ky/docstory/auth/CustomSuccessHandler.java
  src/main/java/com/ky/docstory/auth/OAuth2UserDto.java
  src/main/java/com/ky/docstory/common/code/DocStoryResponseCode.java
  src/main/java/com/ky/docstory/config/Neo4jConfig.java
  src/main/java/com/ky/docstory/config/SecurityConfig.java
  src/main/java/com/ky/docstory/controller/CurrentUserController.java
  src/main/java/com/ky/docstory/controller/UserController.java
  src/main/java/com/ky/docstory/dto/ProfileImage.java
  src/main/java/com/ky/docstory/entity/User.java
  src/main/java/com/ky/docstory/jwt/JWTFilter.java
  src/main/java/com/ky/docstory/jwt/JWTUtil.java
  src/main/java/com/ky/docstory/repository/UserRepository.java
  src/main/java/com/ky/docstory/service/UserService.java
  src/main/resources/application.properties
  src/test/java/com/ky/docstory/jwt/JWTFilterTest.java
Labels: ✨feature

#17 [Feat] : 엔티티 생성
  src/main/java/com/ky/docstory/entity/BaseEntity.java
  src/main/java/com/ky/docstory/entity/File.java
  src/main/java/com/ky/docstory/entity/History.java
  src/main/java/com/ky/docstory/entity/Proposal.java
  src/main/java/com/ky/docstory/entity/Repository.java
  src/main/java/com/ky/docstory/entity/Review.java
  src/main/java/com/ky/docstory/entity/Team.java
  src/main/java/com/ky/docstory/entity/User.java
Labels: ✨feature

#22 [Fix]: CurrentUser 어노테이션 반환 객체 수정
  src/main/java/com/ky/docstory/common/code/DocStoryResponseCode.java
  src/main/java/com/ky/docstory/config/SecurityConfig.java
  src/main/java/com/ky/docstory/controller/CurrentUserController.java
  src/main/java/com/ky/docstory/jwt/JWTFilter.java
  src/test/java/com/ky/docstory/jwt/JWTFilterTest.java
Labels: 🐛bug

#24 [Fix]: Swagger 접속 불가 문제 수정
  src/main/java/com/ky/docstory/config/SecurityConfig.java
  src/main/java/com/ky/docstory/jwt/JWTFilter.java
Labels: 🐛bug

#26 [Fix]: 예외 응답 형식 수정
  src/main/java/com/ky/docstory/jwt/JWTFilter.java
Labels: 🐛bug

#29 [Feat]: Repository, Team 로직 구현
  build.gradle
  src/main/java/com/ky/docstory/common/code/DocStoryResponseCode.java
  src/main/java/com/ky/docstory/common/exception/GlobalExceptionHandler.java
  src/main/java/com/ky/docstory/controller/repository/RepositoryApi.java
  src/main/java/com/ky/docstory/controller/repository/RepositoryController.java
  src/main/java/com/ky/docstory/controller/team/TeamApi.java
  src/main/java/com/ky/docstory/controller/team/TeamController.java
  src/main/java/com/ky/docstory/controller/teaminvite/TeamInviteApi.java
  src/main/java/com/ky/docstory/controller/teaminvite/TeamInviteController.java
  src/main/java/com/ky/docstory/dto/repository/MyRepositoryResponse.java
  src/main/java/com/ky/docstory/dto/repository/RepositoryCreateRequest.java
  src/main/java/com/ky/docstory/dto/repository/RepositoryResponse.java
  src/main/java/com/ky/docstory/dto/team/RoleUpdateRequest.java
  src/main/java/com/ky/docstory/dto/team/RoleUpdateResponse.java
  src/main/java/com/ky/docstory/dto/team/TeamMemberResponse.java
  src/main/java/com/ky/docstory/dto/teaminvite/TeamInviteRequest.java
  src/main/java/com/ky/docstory/dto/teaminvite/TeamInviteResponse.java
  src/main/java/com/ky/docstory/entity/Team.java
  src/main/java/com/ky/docstory/entity/TeamInvite.java
  src/main/java/com/ky/docstory/repository/RepositoryRepository.java
  src/main/java/com/ky/docstory/repository/TeamInviteRepository.java
  src/main/java/com/ky/docstory/repository/TeamRepository.java
  src/main/java/com/ky/docstory/repository/UserRepository.java
  src/main/java/com/ky/docstory/service/repository/RepositoryService.java
  src/main/java/com/ky/docstory/service/repository/RepositoryServiceImpl.java
  src/main/java/com/ky/docstory/service/team/TeamService.java
  src/main/java/com/ky/docstory/service/team/TeamServiceImpl.java
  src/main/java/com/ky/docstory/service/teaminvite/TeamInviteService.java
  src/main/java/com/ky/docstory/service/teaminvite/TeamInviteServiceImpl.java
  src/main/java/com/ky/docstory/swagger/AlreadyHandledErrorResponseWrapper.java
  src/main/java/com/ky/docstory/swagger/BadRequestErrorResponseWrapper.java
  src/main/java/com/ky/docstory/swagger/DuplicateResourceErrorResponseWrapper.java
  src/main/java/com/ky/docstory/swagger/ForbiddenErrorResponseWrapper.java
  src/main/java/com/ky/docstory/swagger/InternalServerErrorResponseWrapper.java
  src/main/java/com/ky/docstory/swagger/MyRepositoryListResponseWrapper.java
  src/main/java/com/ky/docstory/swagger/NotFoundErrorResponseWrapper.java
  src/main/java/com/ky/docstory/swagger/RepositoryCreateResponseWrapper.java
  src/main/java/com/ky/docstory/swagger/RoleUpdateResponseWrapper.java
  src/main/java/com/ky/docstory/swagger/SuccessEmptyResponseWrapper.java
  src/main/java/com/ky/docstory/swagger/TeamInviteResponseWrapper.java
  src/main/java/com/ky/docstory/swagger/TeamMemberListResponseWrapper.java
  src/main/java/com/ky/docstory/swagger/UnauthorizedErrorResponseWrapper.java
Labels: ✨feature
